### ISSUE TITLE
lolisafe setup with plesk

### ISSUE THREAD

**Issue by Hamm3rhart** [WeebDev/chibisafe#227]
Hello,
i tried to install lolisafe on my plesk server. The node part just worked fine but i still can't access the page.
![3659d64d](https://user-images.githubusercontent.com/50116721/102402095-9338d200-3fe4-11eb-94d0-57b58279ae17.png)
For my bad, i don't understand how to import your nginx config to mine. When i tried, nginx won't start anymore. I am using your default config, only with the domain name changed and behind cloudflare. (Nginx isn't compiled, i want to try that after i fixed the issue i have now). If you need anything else to help me, i will provide it as good as i can.

Best wishes,
Hamm3rhart

EDIT1: Error ID is 7041bebd

**Comment by Pitu** [comment]
Sorry but I never used plesk before so I can't be of much help. Unless you can provide with some logs or something it's gonna be very difficult to troubleshoot. 
Feel free to reopen this if you can supply more information!
