### ISSUE TITLE
Investigate using blake3 instead of md5 for faster hashing of files

### ISSUE THREAD

**Issue by Pitu** [WeebDev/chibisafe#242]
Something to take into account is that if we proceed with this then every file in the db needs to be rehashed for consistency.

**Comment by BobbyWibowo** [comment]
> every file in the db needs to be rehashed for consistency.

Unfortunately yes. But with how fast blake3 is in comparison, I can only say, better start as early as possible, fufu

**Comment by Pitu** [comment]
Done f9444691627d6168511a5066553dae6dc0390c58
