### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by acimanx** [WeebDev/chibisafe#256]
**Describe the bug**
Docker installation issue. 

**To Reproduce**
Create fresh debian 10.8.0 system, (standard system utilities + SSH server)
Follow instructions to install docker: https://docs.docker.com/engine/install/debian/
Install docker compose: https://docs.docker.com/compose/install/

**Following https://github.com/WeebDev/chibisafe/blob/master/docs/docker.md**
git clone https://github.com/WeebDev/chibisafe.git
cd chibisafe/docker
mv docker-compose.config.example.yml docker-compose.config.yml
cd nginx
mv chibisafe.moe.http.example.conf chibisafe.moe.conf
cd ..
su
bash chibisafe.sh prod pull
bash chibisafe.sh prod build
bash chibisafe.sh prod up -d

docker ps
1. docker_chibisafe **STATUS up**
2. docker_nginx **STATUS restarting**

docker logs DOCKER_NGINX_CONTAINER_ID
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)

**Comment by acimanx** [comment]
Copying contents of the nginx folder to nginx-data folder plus placing extra mime.types there eliminates previous errors. It's strange, because as I understand dockerfile supposed to copy files from nginx already.
After this actions app still isn't accessible from ports 80,5000 or 5001. Tried to change reverse proxy in nginx to localhost, still without success.
Am I missing something?

**Comment by iCrawl** [comment]
I added a bit more information to the docker documentation, this should clear up things hopefully.

**Comment by acimanx** [comment]
http://localhost returns nginx default template, http://localhost:5000 and http://localhost:5001 unreachable.

**Comment by iCrawl** [comment]
You reverted all the changes you made and pulled the repo for updates, yes?

**Comment by acimanx** [comment]
Tried to install chibisafe again with npm to be sure. Going through setup process enter on everything (defaults), access via http://localhost:5000 works, _http://localhost refused, http://localhost:5001 refused_

Going back to docker: 
1. Removed old containers and images. Clear docker cache via: docker system prune -a. 
2. New git clone
3. Following instruction for http on https://github.com/WeebDev/chibisafe/blob/master/docs/docker.md
4. _http://localhost:5000 refused_, http://localhost welcome to nginx, _http://localhost:5001 refused_
5. To be sure about chrome cache tried in edge browser too.

I can only guess that something wrong with port configuration...
Trying to add 
`        ports:
            - "5000:5000"
            - "5001:5001"` to chibisafe in docker-compose.yml Getting error "empty response" instead of "connection refused" 
So now it means that 3 ports are exposed and working but nginx doesn't catch from backend as supposed?

**Comment by iCrawl** [comment]
Yes, you are not supposed to access those ports directly. They get reversed proxied either over 80 or 443, depending on if you want to use SSL or not.

To circumvent the nginx welcome page you probably forgot to change the `server_name` in the copied `chibisafe.moe.conf` file.
This points to chibisafe.moe on default because chibisafe itself (the private one) is hosted based off this repository.

So if you want to use this with a droplets/VPS IP you will need to change `server_name` to `localhost` or the IP, or you supply your own domain if you access it via a domain.

**Comment by acimanx** [comment]
Thank you, it finally works! I wracked my brain for several hours after your message, because writing port 5000 in docker-compose.yml actually gave me an access to chibisafe frontend and I started to think why nginx is there... until I tried to login or load something.

So the minimal and most essential content of chibisafe.moe.conf is 
```
server {
    server_name localhost;

  location / {
    proxy_pass http://chibisafe:5000;
  }
}
```
Where localhost === DOMAIN variable in docker-compose configs.
And chibisafe in proxy_pass === SERVICE_NAME variable (default chibisafe) in docker-compose configs.

Thanks again @iCrawl , appreciating your help and patience over this issue!

**Comment by iCrawl** [comment]
It's not really a good idea to use this as a "minimal" one.

The most you can remove is the logs, everything else should be kept as it is for security purposes alone already.

This would be the most minimal and most essential one.
```
server {
    listen              80;
    listen              [::]:80;
    server_name         localhost;

    include             nginxconfig.io/security.conf;

    location / {
        proxy_pass http://chibisafe:5000;
        include    nginxconfig.io/proxy.conf;
    }

    include nginxconfig.io/general.conf;
}
```
