### ISSUE TITLE
[BUG] User accounts get disabled when migrating from v3 to v4

### ISSUE THREAD

**Issue by BrandonDusseau** [WeebDev/chibisafe#257]
**Describe the bug**
After migration from lolisafe v3 to chibisafe v4, all non-admin users are disabled and need to be manually re-enabled by an admin account. This results in a confusing, generid "401" error popup.

**To Reproduce**
1. Run `npm run setup`
2. Copy v3's database/db file to chibisafe root
3. Run `node src/api/databaseMigration.js`
4. Start chibisafe v4. No non-admin accounts will work, and existing root credentials are lost.

**Expected behavior**
Non-admin accounts should remain enabled. At the very least, this should be documented in the migration guide.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Pitu** [comment]
Should be fixed in ea0d8aafcfb4b38b562cbe572ae6fc96b44b769f. If you keep having this issue please let me know!
