### ISSUE TITLE
[BUG] Setup process does not honor options to disable registration and public upload

### ISSUE THREAD

**Issue by BrandonDusseau** [WeebDev/chibisafe#258]
**Describe the bug**
When going through the setup process, I chose to NOT allow registration and public upload, but the options wound up set to `true` in the `.env` file anyway.

**To Reproduce**
1. Run `npm run setup`.
2. Choose `n` for both "Allow people to upload files without an account?" and "Allow people to create new accounts?"
3. Complete setup and check the `.env` file. `PUBLIC_MODE` and `USER_ACCOUNTS` will be set to `true`.

**Expected behavior**
`PUBLIC_MODE` and `USER_ACCOUNTS` settings in `.env` should respect the selection during setup.

**Screenshots**
![image](https://user-images.githubusercontent.com/3901864/108609419-bc3a6200-739b-11eb-8cc2-4cbdcdc5ff73.png)
_'n' is selected for both public upload and user registration._

![image](https://user-images.githubusercontent.com/3901864/108609432-d4aa7c80-739b-11eb-81f3-a6b3865c9847.png)
_Both options are set to true in the resulting configuration._

**Additional context**
N/A

**Comment by Pitu** [comment]
This should be fixed in e09fcf70d86bc5607264a7d93ef3451d08974e4c. If you keep experiencing this issue please let me know!
