### ISSUE TITLE
[BUG] Registration closed even if setting is on

### ISSUE THREAD

**Issue by Mxnuuel** [WeebDev/chibisafe#259]
**Describe the bug**
Even with "USER_ACCOUNTS=true" in the .env you can't register on the website.

**To Reproduce**
1. Setup chibisafe with user_accounts false
2. edit .env
3. restart service

**Expected behavior**
Registrations being turned on.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/45440100/110638483-ec14a280-81ae-11eb-859b-77f7c99a8ef1.png)
![grafik](https://user-images.githubusercontent.com/45440100/110638606-0c446180-81af-11eb-9b53-e9e5cce95600.png)
![grafik](https://user-images.githubusercontent.com/45440100/110638512-f2a31a00-81ae-11eb-9a83-1eb10dbe8922.png)

**Comment by Pitu** [comment]
If you edit the `.env` file you need to rebuild chibisafe right after for the changes to be propagated to the frontend. You can do so by running `npm run build`. Let me know if this fixes it!

**Comment by Pitu** [comment]
And toggling the options from within the admin panel in the website is currently not working, so whatever you change in the `.env` file please rebuild right after

**Comment by Pitu** [comment]
Feel free to open this issue again if you are still having problems
