### ISSUE TITLE
[FEATURE REQUEST] Add Screenshots

### ISSUE THREAD

**Issue by SuperSandro2000** [WeebDev/chibisafe#261]
I wanted to checkout how chibisafe looks and what options it has. I can understand that the registration is closed but some screenshots would be nice to know how the program looks and if I should set it up or not.

**Comment by Pitu** [comment]
That's a very nice suggestion, I'll take some screenshot and update the docs. Thank you!

**Comment by Pitu** [comment]
Added in 771d8494ef1ec6c74a4bc6862dfd1a04ed5d569e

**Comment by SuperSandro2000** [comment]
Thanks!
