### ISSUE TITLE
problem with the docker instructions

### ISSUE THREAD

**Issue by bonevays** [WeebDev/chibisafe#263]
Hi, not sure if it's a big or a feature but I could not find a file similar to `Copy either chibisafe.moe.http.example.conf or chibisafe.moe.https.example.conf to chibisafe.moe.conf for either HTTP or HTTPS` , mentioned in the docker instructions. Perhaps someone can solve the mystery faster than me? Thanks!

**Comment by Pitu** [comment]
You can find the file in the `docker/nginx` folder, like so https://github.com/WeebDev/chibisafe/blob/master/docker/nginx/chibisafe.moe.http.example.conf
