### ISSUE TITLE
mysql default charset used for connection

### ISSUE THREAD

**Issue by Devices** [WeebDev/chibisafe#282]
I set up a mysql database with utf8mb4 charset, but when the setup tries to put something in the settings table, the following error is produced:

[database error.txt](https://github.com/WeebDev/chibisafe/files/6741555/database.error.txt)

I believe this is because the database connection is initiated as UTF8 instead of UTF8mb4, despite the usage of emoji in the setup process. As far as I know, emoji requires an UTF8mb4 charset. From the documention of the mysql module:

>`charset`: The charset for the connection. This is called "collation" in the SQL-level of MySQL (like `utf8_general_ci`). If a SQL-level charset is specified (like `utf8mb4`) then the default collation for that charset is used. (Default: `'UTF8_GENERAL_CI'`)

At least I cannot find utf8mb4 being specified anywhere in the code.

So if this is true, would it make sense to initialise the database connection with the proper charset?
Alternatively, the emoji can also be dropped for better compatibility.

**Comment by Pitu** [comment]
According to [knex docs](https://knexjs.org/#Schema-charset), we can only set the charset for MySQL using this library and it has to be done during creation of the tables. That being said and chibisafe shipping with sqlite support by default you could edit the relevant files (4 of them) to add the charset if you really want to use emoji, or drop them as you suggested.

> Sets the charset for the database table, only available within a createTable call, and only applicable to MySQL.

I'm in the middle of rewriting chibisafe so I'll take this into account for the next version.

**Comment by Devices** [comment]
From what I can see, the tables are created with the proper charset:
>| settings | CREATE TABLE `settings` (
>  `key` varchar(255) DEFAULT NULL,
>  `value` varchar(255) DEFAULT NULL
>) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
I think it has more to do with the database connection used with the mysql module and not knex, but I am not well versed in these kind of things.
After I removed the emoji from some files, the setup runs correctly. Thanks for the suggestion.

**Comment by Pitu** [comment]
Glad you could sort it out, I'll keep an eye for this in the rewrite.
Since most people use chibisafe with sqlite or postgresql this hasn't been brought up until now, so thanks for letting me know!
