### ISSUE TITLE
[BUG] Can't launch the site

### ISSUE THREAD

**Issue by Maxence1111** [WeebDev/chibisafe#310]
**Describe the bug**

**To Reproduce**
1. Be on windows
2. install all things correctly
3. launch the application with pm2 start pm2.json

**Expected behavior**
That should work i installed everythings

**Screenshots**
![Capture d’écran 2021-11-17 163141](https://user-images.githubusercontent.com/73644049/142230551-76465400-9ff2-44b2-bf20-30e852a0cf6d.jpg)

**Comment by Aareksio** [comment]
```
node -v
npm -v
pm2 -v
```
Please execute the above in CMD one by one.

**Comment by yesBad** [comment]
and could you use either the Discord or the github issues, seems a bit dumb to post it in both.

**Comment by Maxence1111** [comment]
Node -v = 12.13.0
npm -v - 8.1.3
pm2 = 5.1.2 thx for your help
