### ISSUE TITLE
[BUG] Error  ERROR  connect ECONNREFUSED 127.0.0.1:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:16)

### ISSUE THREAD

**Issue by Maxence1111** [WeebDev/chibisafe#311]
**Describe the bug**
I got this error when i try to access to the site.

**To Reproduce**
1. Be on debian
2. Launch the site in localhost

**Expected behavior**
That should work

**Screenshots**
![image](https://user-images.githubusercontent.com/73644049/142408329-6164fb32-3bb2-43c1-8af2-241dd9afa062.png)

**Comment by yesBad** [comment]
Fix
![Discord_SzxjP7BBls](https://user-images.githubusercontent.com/87938689/142412470-316cbcf5-3bb5-4e2f-be14-10a29e6fa037.png)
:
