### ISSUE TITLE
[ Question ] Host without Domain

### ISSUE THREAD

**Issue by Skwll** [WeebDev/chibisafe#316]
Hey

How exactly can I set this up to only use the public IP of my server and without nginx?

I tried to do it like #311 but with public IP.

It won't work and crash the server.

**Comment by yesBad** [comment]
Why do you even want to host it without NGINX & domain

**Comment by Skwll** [comment]
Bc I just want to test it

**Comment by yesBad** [comment]
Use it on your localhost like in #311 xd?

**Comment by Skwll** [comment]
Got it working (just added http://localhost:5000 instead of http://realip:5000 as domain)
