### ISSUE TITLE
[FEATURE REQUEST] Discord Embedded Link / Social Media Embedded Link

### ISSUE THREAD

**Issue by Minecodes** [WeebDev/chibisafe#330]
Can you please add a function to have a link preview on WhatsApp, Discord, etc.? This would be very handy, especially since it already has this on the home page and adjustable via the admin settings. That would be very useful.

![IMG_20220424_103834.jpg](https://user-images.githubusercontent.com/65566012/164967944-a4f82bbe-3880-41b9-853b-39a7e8e40619.jpg)

**Comment by Permanently** [comment]
This already exists.

**Comment by ggtylerr** [comment]
I believe they were talking about image/file embeds, which don't exist. Yes, media files are technically embedded, but they don't have anything around it, like this:
![image](https://github.com/chibisafe/chibisafe/assets/28498877/461fcec9-3b27-46af-86d4-f0f773399192)
